# Generated by Django 4.1.1 on 2022-10-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_remove_post_tag_delete_tag_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='total_comments',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
