# Generated by Django 4.1.1 on 2022-10-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customer_product_image_on_hover_product_people_voted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product',
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='shop.product'),
        ),
    ]
