# Generated by Django 4.1.1 on 2022-10-07 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_customer_name_customer_phone_number_customer_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcartitem',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.customer'),
            preserve_default=False,
        ),
    ]
