# Generated by Django 4.1.1 on 2022-10-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_customer_is_admin_customer_is_banned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='total_messages',
            field=models.IntegerField(default=0),
        ),
    ]
