# Generated by Django 4.1.1 on 2022-10-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_customer_total_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(default='../static/img/default_avatar.png', upload_to='users'),
        ),
    ]
