# Generated by Django 4.1.1 on 2022-10-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_customer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='timezone',
            field=models.CharField(default='Asia/Almaty', max_length=255),
        ),
    ]
