# Generated by Django 4.1.1 on 2022-10-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_customer_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='shop.product'),
        ),
    ]
